/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "EMS_OUT.h"
#include "EMS_OUT_aliases.h"
#include "PWM_2.h"
#include "Clock_1.h"
#include "IDAC_1.h"
#include "DAC.h"
#include "DAC_aliases.h"
#include "PWM_1.h"
#include "Clock_3.h"
#include "Control_Reg_1.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "ULTRA_NAND.h"
#include "ULTRA_NAND_aliases.h"
#include "STEP_DOWN.h"
#include "STEP_DOWN_aliases.h"
#include "AD9833_SDATA.h"
#include "AD9833_SDATA_aliases.h"
#include "AD9833_SCLK.h"
#include "AD9833_SCLK_aliases.h"
#include "AD9833_FSYNC.h"
#include "AD9833_FSYNC_aliases.h"
#include "Control_Reg_2.h"
#include "BUZZER.h"
#include "BUZZER_aliases.h"
#include "isr_select.h"
#include "isr_start_stop.h"
#include "isr_button_down.h"
#include "isr_button_up.h"
#include "BUTTON_UP.h"
#include "BUTTON_UP_aliases.h"
#include "BUTTON_DOWN.h"
#include "BUTTON_DOWN_aliases.h"
#include "START_STOP.h"
#include "START_STOP_aliases.h"
#include "SELECT_PIN.h"
#include "SELECT_PIN_aliases.h"
#include "Clock_4.h"
#include "LCD.h"
#include "EMS_SAFTY.h"
#include "EMS_SAFTY_aliases.h"
#include "TOUCH_UP.h"
#include "TOUCH_UP_aliases.h"
#include "Clock_5.h"
#include "ISR_SCHEDULAR.h"
#include "Timer_1.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

